export const AppRoutes = Object.freeze({
  Home: "/",
  About: "/about-us",
  Contact: "/contact-us",
  Cart: "/cart",
  Profile: "/profile",
  Wishlist: "/wishlist",
  BuyerOrders: "/buyer-orders",
  ProductDetails: "/product/:productId",
  PublishProduct: "/product/publish",
  RiderOrdersToDeliver: "/rider/orders-to-deliver",
  RiderOrdersReturnRequests: "/rider/orders-return-requests",
  RiderOrderHistory: "/rider/orders-history",
  Registration: "register/:role",
  Invalid: "*",
});
