export const AppRoutes = Object.freeze({
  Home: "/",
  About: "/about-us",
  Contact: "/contact-us",
  Cart: "/cart",
  Admin: "/admin",
  Profile: "/profile",
  Wishlist: "/wishlist",
  BuyerOrders: "/buyer-orders",
  SellerDashboard: "/seller/dashboard",
  StoreDetails: "/store/:storeId",
  ProductDetails: "/product/:productId",
  OrderDetails: "/order-details/:productId",
  PublishProduct: "/product/publish",
  RegisterStore: "/register/store",
  RiderOrdersToDeliver: "/rider/orders-to-deliver",
  RiderOrdersReturnRequests: "/rider/orders-return-requests",
  RiderOrderHistory: "/rider/orders-history",
  Registration: "register",
  Invalid: "*",
});
